### ISSUE TITLE
Unable to install via Carthage

### ISSUE THREAD

**Issue by zdnk** [exponea/exponea-ios-sdk#28]
<img width="489" alt="Screenshot 2021-04-27 at 15 35 51" src="https://user-images.githubusercontent.com/2551911/116250710-40c7a900-a76e-11eb-9fde-73b69c86371a.png">

looks like you update the code to better support SPM, but forgot to do the same for other package managers :)

also, with SPM, you needs exclude plists from from sources, others it will yield warnings

**Comment by michaela-dev** [comment]
Hi @zdnk, what XCode are you using? There were some problems with Carthage and XCode 12, where the Carthage build can fail due to duplicate architectures, and dependencies are not properly added. 
To fix this, we added carthage.sh file into exponea-ios-sdk GitHub:

https://github.com/exponea/exponea-ios-sdk/blob/master/carthage.sh

If you are still facing this issue, when installing via Carthage, try downloading this file, placing it in your project folder, and run it:
./carthage.sh build --platform iOS

Also, please make sure you added ExponeaSDK.framework and ExponeaSDKNotifications.framework files from 
<your project path>/Carthage/Build/iOS to "Frameworks, Libraries and Embedded Content" section in your target settings in XCode. 

We will make documentation for installing via Carthage more detailed and clear ASAP. We also plan to add a troubleshooting section, to cover issues like this.

If you are still not able to make it work, please send me more info. Thanks!
